//! Copyright (c) 2005–2025 IKH Software, Inc.
//!
//! Released under the terms of the GNU Lesser General Public License, version 3.0
//! or (at your option) any later version (LGPL-3.0-or-later).
//!     
//! Runtime support library for lexers and parsers generated by
//! [`parlex-gen`](https://crates.io/crates/parlex-gen).
//!
//! `parlex` defines the generic traits and core data structures that
//! generated lexers and parsers use at runtime. You typically depend on
//! this crate alongside the code produced by the `alex` (lexer) and `aslr`
//! (parser) generators from `parlex-gen`. See the crate README for a feature
//! overview, usage, and docs.rs links.
//!
//! - Generic traits for lexical analysis and parsing
//! - Core data structures used by generated code
//! - Foundation for building custom lexers and parsers
//!
//! For more background and examples, see the `parlex` README on GitHub and
//! docs.rs.
//!
//! # Crates.io
//! Published at [crates.io/crates/parlex](https://crates.io/crates/parlex).


mod lexer;
mod parser;

pub use crate::lexer::{Lexer, LexerCtx, LexerData, LexerMode, LexerRule, LexerStats, Token};
pub use crate::parser::{
    Parser, ParserAction, ParserAmbigID, ParserCtx, ParserData, ParserProdID, ParserStateID,
    ParserStats, ParserTokenID,
};
